### ISSUE TITLE
hi! We noticed that there are *.z02 files in the dataset you released, such as the youtube folder. Does this have to be downloaded?

### ISSUE THREAD

**Issue by githuboflk** [SparkleXFantasy/MM-Det#2]

**Comment by wclemonade** [comment]
You must download it, otherwise the files will be missing when extracting.

**Comment by githuboflk** [comment]
@SparkleXFantasy @wclemonade Thanks for your reply! Great job!

**Comment by saimeur** [comment]
Hi @SparkleXFantasy, I'm not really familiar with multi-part zip files, and I'm struggling to unzip the data from YouTube and Zeroscope.

For the YouTube dataset, I tried `cat 0_real.z01 0_real.z02 0_real.zip > fullfile.zip`, then `unzip fullfile.zip`, but I get this error message:  
```
Archive:  fullfile.zip
error: End-of-centdir-64 signature not where expected (prepended bytes?)
  (attempting to process anyway)
warning [fullfile.zip]:  zipfile claims to be the last disk of a multi-part archive;
  attempting to process anyway, assuming all parts have been concatenated
  together in order. Expect "errors" and warnings... true multi-part support
  doesn't exist yet (coming soon).
warning [fullfile.zip]:  8589934592 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  8589934596
  (attempting to re-compensate)
   creating: 0_real/
error: invalid zip file with overlapped components (possible zip bomb)
```

I get the same error when I try `cat 0_real.z01 0_real.z02 0_real.zip > fullfile.zip`. How can I unzip all the videos from the YouTube video dataset and Zeroscope?

PS: I'm using Linux.

**Comment by SparkleXFantasy** [comment]
Hi. I successfully run "7z x 0_real.zip" to unzip all files in "0_real.z*". I hope it is helpful to you.

**Comment by saimeur** [comment]
Thank you, it worked for me :)
