### ISSUE TITLE
Why disable st initialization in test.py

### ISSUE THREAD

**Issue by XizhiMaLY** [SparkleXFantasy/MM-Det#5]
Hi!
I noticed that in test.py line22,23
```
config['st_pretrained'] = False

config['st_ckpt'] = None   # disable initialization
```
will prevent st model from loading pretrained checkpoint, which generates a randomly initialized st model.

However, I ran the test on videocrafter1 dataset and auc is 1(first 60). Which means a pretrained MMFR and randomized ST model is good enough?

Best wishes and looking forward to your kind reply!

**Comment by M2F2-Net** [comment]
Hi. 
> Codes in test.py line22,23 will prevent st model from loading pretrained checkpoint, which generates a randomly initialized st model.
The funtionality of these two lines is to disable the initialization of the ST branch. 
In test.py, we suppose that a pretrained checkpoint is loaded for evaluation. In this case, the real checkpoint is loaded at test.py#L46, including the weights for ST branch. Therefore, we add test.py#L22-23 to skip the initialization stage for acceleration. I hope this message is helpful to you.

**Comment by SparkleXFantasy** [comment]
Hi.

> Codes in test.py line22,23 will prevent st model from loading pretrained checkpoint, which generates a randomly initialized st model.

The funtionality of these two lines is to disable the initialization of the ST branch.
In test.py, we suppose that a pretrained checkpoint is loaded for evaluation. In this case, the real checkpoint is loaded at test.py#L46, including the weights for ST branch. Therefore, we add test.py#L22-23 to skip the initialization stage for acceleration. I hope this message is helpful to you.

**Comment by XizhiMaLY** [comment]
That's very clear, many thanks!
